name: RocketBans
version: @version@
main: me.lorenzo0111.rocketbans.bukkit.RocketBans
api-version: '1.13'
authors: [Lorenzo0111]
commands:
  rocketbans:
    aliases:
      - rb
      - ban
      - tempban
      - unban
      - kick
      - mute
      - tempmute
      - unmute
      - history